1-Docker_server_hostname: 0.0.0.0

2-Docker_network_name: galasa

3-Container_restart_policy: always

4-Api_container_name: galasa-api

5-Api_volume_name: galasa-api

6-Api_mount_target: /galasa/data/galasa

7-Api_container_port: 8181

8-Controller_container_name: galasa-controller

9-Cps_container_name: galasa-cps

10-Cps_volume_name: galasa-etcd

11-Cps_mount_target: /var/run/etcd/default.etcd

12-Cps_container_port: 2379

13-Ras_container_name: galasa-ras

14-Ras_volume_name: galasa-couchdb

15-Ras_mount_target: /var/run/etcd/default.etcd

16-Ras_container_port: 5984

17-ResourceMonitor_container_name: galasa-resmon

18-Resource_container_name: galasa-resources

19-Resource_container_port: 8080

20-Simbank_container_name: galasa

21-Simbank_port: 2080

